# config.ini
# Grid
algorithm   = 2

# Simulation
N_STEPS     = 5000
FREQ_SAVE   = 10
DT          = 0.025
GRAVITY     = 9.81
DX          = 1.0

# Erosion constants
KC          = 1.0
KS          = 0.05
KD          = 0.05
KE          = 0.2

# Rain
RAIN_AMOUNT = 0.1
RAIN_DROPS  = 50.0
RAIN_STOP   = 1000

# Water source level
WATER_LEVEL = 0.005