# config.ini
# Grid
algorithm   = 6

# Simulation
N_STEPS     = 1000000
FREQ_SAVE   = 10000
DT          = 0.0001
GRAVITY     = 9.81
DX          = 1.0

# Erosion constants
KC          = 1.0
KS          = 0.25
KD          = 0.25
KE          = 0.25

# Rain
RAIN_AMOUNT = 0.1
RAIN_DROPS  = 250.0
RAIN_STOP   = 100000

# Water source level
WATER_LEVEL = 0.005