# config.ini
# Grid
algorithm   = 6

# Simulation
N_STEPS     = 5000
FREQ_SAVE   = 10
DT          = 0.05
GRAVITY     = 9.81
DX          = 1.0

# Erosion constants
KC          = 1.0
KS          = 0.1
KD          = 0.1
KE          = 0.25

# Rain
RAIN_AMOUNT = 0.2
RAIN_DROPS  = 100.0
RAIN_STOP   = 1000

# Water source level
WATER_LEVEL = 0.005